
import React, { createContext, useContext, useState, useEffect, ReactNode } from 'react';
import { Language } from '../types';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
  formatPrice: (price: number) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations: Record<Language, Record<string, string>> = {
  zh: {
    'app.name': 'DESCU',
    'nav.search': '搜索宝贝、车辆、房产...',
    'nav.sell': '卖闲置',
    'nav.home': '首页',
    'nav.cart': '购物车',
    'nav.favorites': '我的收藏',
    'nav.profile': '我的',
    'nav.login': '登录',
    'nav.chat': '消息',
    'nav.notifications': '提醒',
    'login.required': '需要登录',
    'login.prompt': '请登录以继续操作',
    'login.google': '使用 Google 登录',
    'login.terms': '继续即表示同意服务条款',
    'hero.title': '本地买卖，方便快捷',
    'hero.subtitle': '您身边的AI智能二手平台',
    'hero.cta': '立即探索',
    'list.header': '为您推荐',
    'list.search_results': '搜索结果',
    'list.items_count': '件商品',
    'list.loading_loc': '正在定位...',
    'list.loc_denied': '请开启定位',
    'list.loc_success': '附近',
    'list.empty': '暂无商品，快来发布第一个吧！',
    'list.no_results': '没有找到相关商品',
    'list.view_all': '查看所有商品',
    'list.load_more': '加载更多',
    'list.loading_more': '加载中...',
    'card.nearby': '附近',
    'chat.ask_price': '议价',
    'chat.offer_title': '提出议价',
    'chat.current_price': '当前价格',
    'chat.your_offer': '您的出价',
    'chat.send_offer': '发送议价',
    'chat.cancel': '取消',
    'card.add_cart': '想要',
    'card.in_cart': '已添加',
    'card.promoted': '推广',
    'modal.title': '发布闲置',
    'modal.upload_text': '点击上传照片',
    'modal.upload_hint': 'AI将自动识别并填写信息',
    'modal.change_img': '更改图片',
    'modal.analyzing': 'AI 正在分析图片生成描述...',
    'modal.analyzed': 'AI 已为您自动填充信息',
    'modal.label.title': '标题',
    'modal.ph.title': '例如：95成新 iPhone 14',
    'modal.label.price': '价格',
    'modal.label.category': '分类',
    'modal.label.delivery': '交易方式',
    'modal.label.desc': '详细描述',
    'modal.ph.desc': '描述一下物品的新旧程度、入手渠道等...',
    'modal.loc.loading': '定位中...',
    'modal.loc.success': '位置已锁定',
    'modal.submit': '立即发布',
    'modal.submit.analyzing': '分析中...',
    'modal.policy_hint': '发布即表示您同意我们的内容政策，严禁发布仇恨言论或虚假政治信息。',
    'modal.ai_error': 'AI分析失败，请检查网络或稍后重试',
    'cart.title': '购物车',
    'cart.empty': '购物车空空如也',
    'cart.go_shop': '去逛逛',
    'cart.total': '合计',
    'cart.checkout': '立即结算',
    'cart.processing': '处理中...',
    'cart.success': '下单成功！',
    'cat.all': '全部',
    'cat.electronics': '数码',
    'cat.furniture': '家具',
    'cat.clothing': '服饰',
    'cat.books': '图书',
    'cat.sports': '运动',
    'cat.vehicles': '车辆',
    'cat.real_estate': '房产',
    'cat.services': '服务',
    'cat.other': '其他',
    // Subcategories - Electronics
    'subcat.phones': '手机',
    'subcat.laptops': '笔记本',
    'subcat.tablets': '平板',
    'subcat.cameras': '相机',
    'subcat.audio': '音响',
    'subcat.gaming': '游戏设备',
    'subcat.wearables': '穿戴设备',
    'subcat.accessories': '配件',
    // Subcategories - Vehicles
    'subcat.cars': '汽车',
    'subcat.motorcycles': '摩托车',
    'subcat.bicycles': '自行车',
    'subcat.trucks': '卡车',
    'subcat.parts': '零件',
    // Subcategories - RealEstate
    'subcat.apartments': '公寓',
    'subcat.houses': '别墅',
    'subcat.land': '土地',
    'subcat.commercial': '商铺',
    'subcat.rentals': '出租',
    // Subcategories - Furniture
    'subcat.sofas': '沙发',
    'subcat.beds': '床',
    'subcat.tables': '桌椅',
    'subcat.storage': '储物柜',
    'subcat.office': '办公家具',
    // Subcategories - Clothing
    'subcat.women': '女装',
    'subcat.men': '男装',
    'subcat.kids': '童装',
    'subcat.shoes': '鞋类',
    'subcat.fashion_accessories': '配饰',
    // Subcategories - Sports
    'subcat.fitness': '健身',
    'subcat.outdoor': '户外',
    'subcat.team_sports': '球类',
    'subcat.water_sports': '水上运动',
    'subcat.winter_sports': '冬季运动',
    // Subcategories - Services
    'subcat.repair': '维修',
    'subcat.cleaning': '清洁',
    'subcat.teaching': '教学',
    'subcat.beauty': '美容',
    'subcat.moving': '搬家',
    // Subcategories - Books
    'subcat.fiction': '小说',
    'subcat.textbooks': '教材',
    'subcat.children': '儿童读物',
    'subcat.magazines': '杂志',
    'subcat.comics': '漫画',
    // Subcategories - Other
    'subcat.collectibles': '收藏品',
    'subcat.pets': '宠物用品',
    'subcat.food': '食品',
    'subcat.plants': '植物',
    'delivery.meetup': '当面交易',
    'delivery.shipping': '快递发货',
    'delivery.both': '面交/快递',
    'detail.back': '返回',
    'detail.seller': '卖家信息',
    'detail.verified': '已认证卖家',
    'detail.contact': '联系卖家',
    'detail.posted': '发布于',
    'detail.location': '交易地点',
    'detail.delivery': '配送方式',
    'detail.desc_title': '商品详情',
    'detail.recommend': '猜你喜欢',
    'detail.report': '举报此内容',
    'profile.title': '个人中心',
    'profile.avatar': '头像',
    'profile.change_avatar': '更换头像',
    'profile.name': '昵称',
    'profile.email': '邮箱',
    'profile.save': '保存修改',
    'profile.saved': '保存成功！',
    'profile.listings': '我发布的',
    'profile.no_listings': '暂无发布记录',
    'profile.verify_title': '身份认证',
    'profile.verify_desc': '提交身份证件，获得蓝盾标识，做值得信赖的卖家。',
    'profile.get_verified': '提交证件 (免费)',
    'profile.verifying': '审核中...',
    'profile.is_verified': '身份已认证',
    'profile.boost': '推广',
    'profile.safety_policies': '安全与政策',
    'profile.content_policy': '内容与政治规范',
    'profile.privacy_policy': '隐私政策',
    'profile.buying': '我的订单',
    'profile.selling': '我的销售',
    'profile.payouts': '收款设置',
    'profile.payouts_desc': '绑定银行账户以接收销售款项 (支持Stripe)。',
    'profile.setup_payouts': '立即绑定',
    'report.title': '举报内容',
    'report.reason': '举报原因',
    'report.reason.misinfo': '政治虚假信息',
    'report.reason.hate': '仇恨言论或歧视',
    'report.reason.scam': '诈骗或误导',
    'report.reason.prohibited': '禁止销售的物品',
    'report.reason.sensitive': '敏感政治宣传',
    'report.submit': '提交举报',
    'report.success': '感谢您的反馈，我们将进行审核。',
    'time.today': '今天',
    'time.days_ago': '{0}天前',
    'chat.inbox': '消息列表',
    'chat.type': '输入消息...',
    'chat.send': '发送',
    'chat.no_msgs': '暂无消息',
    'chat.empty_inbox': '还没有开始任何对话',
    'chat.you': '你',
    // 议价相关
    'nego.title': '议价',
    'nego.original_price': '原价',
    'nego.your_offer': '出价',
    'nego.counter_price': '卖家报价',
    'nego.final_price': '成交价',
    'nego.status.pending': '待响应',
    'nego.status.accepted': '已接受',
    'nego.status.rejected': '已拒绝',
    'nego.status.countered': '卖家还价',
    'nego.action.accept': '接受',
    'nego.action.counter': '还价',
    'nego.action.reject': '拒绝',
    'nego.confirm_counter': '确认还价',
    'nego.cancel': '取消',
    'nego.success.accepted': '议价成功！价格',
    'nego.success.rejected': '卖家拒绝了此议价',
    'nego.success.countered': '卖家提出新报价',
    'nego.enter_price': '输入您的报价',
    'nego.failed': '响应议价失败，请重试',
    // 聊天列表
    'chat.tab.all': '全部',
    'chat.tab.active': '进行中',
    'chat.tab.inquiring': '咨询中',
    'chat.tab.completed': '已完成',
    'chat.unknown_product': '未知商品',
    'chat.view_details': '点击查看详情',
    'chat.conversations': '对话',
    'chat.empty_inbox_hint': '从商品页面开始聊天吧',
    'chat.no_chats_in_tab': '此分类暂无对话',
    'chat.buyers': '位买家',
    'chat.hide': '隐藏',
    'chat.delete': '删除',
    'chat.trading': '交易中',
    'chat.hide_conversation': '隐藏对话',
    'chat.delete_conversation': '删除对话',
    'chat.delete_confirm': '确定删除此对话？此操作不可撤销。',
    'chat.hidden_count': '个对话已隐藏',
    'chat.online': '活跃中',
    'chat.view_product': '点击查看详情',
    'chat.report_user': '举报用户',
    'chat.block_user': '屏蔽用户',
    'chat.user_reported': '已举报',
    'chat.user_blocked': '已屏蔽',
    'chat.loading': '加载中...',
    'chat.load_earlier': '加载更早的消息',
    'chat.send_failed': '发送失败，请重试',
    'chat.make_offer': '议价',
    'chat.share_location': '分享位置',
    'chat.arrange_meetup': '约定时间',
    'chat.arrange_meetup_btn': '安排见面',
    'chat.deleted_success': '聊天记录已删除',
    'list.search_hint': '试试换个关键词或更笼统的搜索',
    'list.empty_hint': '成为该分类的第一个卖家！',
    'product.rate_seller': '评价卖家',
    'product.share': '分享',
    'profile.reviews': '评价',
    'nav.logout': '退出登录',
    // Toast 消息
    'toast.login_failed': '登录验证失败',
    'toast.profile_updated': '个人资料已更新',
    'toast.update_failed': '更新失败',
    'toast.product_published': '🎉 商品发布成功！',
    'toast.product_publish_failed': '❌ 商品发布失败',
    'toast.please_login': '请先登录',
    'toast.favorite_added': '已添加到收藏',
    'toast.favorite_removed': '已从收藏移除',
    'toast.favorite_update_failed': '收藏更新失败',
    'toast.chat_open_failed': '❌ 无法打开聊天,请稍后重试',
    'toast.message_send_failed': '❌ 消息发送失败,请重试',
    'toast.load_failed': '加载失败',
    'toast.upload_failed': '上传失败,请重试',
  },
  en: {
    'app.name': 'DESCU',
    'nav.search': 'Search items, cars, homes...',
    'nav.sell': 'Sell',
    'nav.home': 'Home',
    'nav.cart': 'Cart',
    'nav.favorites': 'Favorites',
    'nav.profile': 'Profile',
    'nav.login': 'Login',
    'nav.chat': 'Chat',
    'nav.notifications': 'Alerts',
    'login.required': 'Login Required',
    'login.prompt': 'Please log in to continue',
    'login.google': 'Continue with Google',
    'login.terms': 'By continuing, you agree to our Terms',
    'hero.title': 'Buy Local, Sell in a Flash',
    'hero.subtitle': 'Your AI-powered neighborhood marketplace. Find hidden gems within 5km.',
    'hero.cta': 'Explore Now',
    'list.header': 'Recommended for You',
    'list.search_results': 'Search Results',
    'list.items_count': 'items',
    'list.loading_loc': 'Locating...',
    'list.loc_denied': 'Enable Location',
    'list.loc_success': 'Nearby',
    'list.empty': 'No items yet. Be the first to sell!',
    'list.no_results': 'No items found',
    'list.view_all': 'View All',
    'list.load_more': 'Load More',
    'list.loading_more': 'Loading...',
    'card.nearby': 'Nearby',
    'chat.ask_price': 'Make Offer',
    'chat.offer_title': 'Make an Offer',
    'chat.current_price': 'Current Price',
    'chat.your_offer': 'Your Offer',
    'chat.send_offer': 'Send Offer',
    'chat.cancel': 'Cancel',
    'card.add_cart': 'Add',
    'card.in_cart': 'Added',
    'card.promoted': 'Promoted',
    'modal.title': 'List Item',
    'modal.upload_text': 'Upload Photo',
    'modal.upload_hint': 'AI will auto-fill details',
    'modal.change_img': 'Change Photo',
    'modal.analyzing': 'AI analyzing...',
    'modal.analyzed': 'AI details generated',
    'modal.label.title': 'Title',
    'modal.ph.title': 'e.g., Like new iPhone 14',
    'modal.label.price': 'Price',
    'modal.label.category': 'Category',
    'modal.label.delivery': 'Delivery Method',
    'modal.label.desc': 'Description',
    'modal.ph.desc': 'Describe condition, usage, etc...',
    'modal.loc.loading': 'Locating...',
    'modal.loc.success': 'Location Locked',
    'modal.submit': 'Post Listing',
    'modal.submit.analyzing': 'Analyzing...',
    'modal.policy_hint': 'By posting, you agree to our policies. Hate speech and political misinformation are strictly prohibited.',
    'modal.ai_error': 'AI analysis failed. Please check connection or try again.',
    'cart.title': 'Cart',
    'cart.empty': 'Your cart is empty',
    'cart.go_shop': 'Go Shopping',
    'cart.total': 'Total',
    'cart.checkout': 'Checkout',
    'cart.processing': 'Processing...',
    'cart.success': 'Order Placed!',
    'cat.all': 'All',
    'cat.electronics': 'Electronics',
    'cat.furniture': 'Furniture',
    'cat.clothing': 'Clothing',
    'cat.books': 'Books',
    'cat.sports': 'Sports',
    'cat.vehicles': 'Vehicles',
    'cat.real_estate': 'Real Estate',
    'cat.services': 'Services',
    'cat.other': 'Other',
    // Subcategories - Electronics
    'subcat.phones': 'Phones',
    'subcat.laptops': 'Laptops',
    'subcat.tablets': 'Tablets',
    'subcat.cameras': 'Cameras',
    'subcat.audio': 'Audio',
    'subcat.gaming': 'Gaming',
    'subcat.wearables': 'Wearables',
    'subcat.accessories': 'Accessories',
    // Subcategories - Vehicles
    'subcat.cars': 'Cars',
    'subcat.motorcycles': 'Motorcycles',
    'subcat.bicycles': 'Bicycles',
    'subcat.trucks': 'Trucks',
    'subcat.parts': 'Parts',
    // Subcategories - RealEstate
    'subcat.apartments': 'Apartments',
    'subcat.houses': 'Houses',
    'subcat.land': 'Land',
    'subcat.commercial': 'Commercial',
    'subcat.rentals': 'Rentals',
    // Subcategories - Furniture
    'subcat.sofas': 'Sofas',
    'subcat.beds': 'Beds',
    'subcat.tables': 'Tables & Chairs',
    'subcat.storage': 'Storage',
    'subcat.office': 'Office Furniture',
    // Subcategories - Clothing
    'subcat.women': 'Women',
    'subcat.men': 'Men',
    'subcat.kids': 'Kids',
    'subcat.shoes': 'Shoes',
    'subcat.fashion_accessories': 'Fashion Accessories',
    // Subcategories - Sports
    'subcat.fitness': 'Fitness',
    'subcat.outdoor': 'Outdoor',
    'subcat.team_sports': 'Team Sports',
    'subcat.water_sports': 'Water Sports',
    'subcat.winter_sports': 'Winter Sports',
    // Subcategories - Services
    'subcat.repair': 'Repair',
    'subcat.cleaning': 'Cleaning',
    'subcat.teaching': 'Tutoring',
    'subcat.beauty': 'Beauty',
    'subcat.moving': 'Moving',
    // Subcategories - Books
    'subcat.fiction': 'Fiction',
    'subcat.textbooks': 'Textbooks',
    'subcat.children': 'Children',
    'subcat.magazines': 'Magazines',
    'subcat.comics': 'Comics',
    // Subcategories - Other
    'subcat.collectibles': 'Collectibles',
    'subcat.pets': 'Pet Supplies',
    'subcat.food': 'Food',
    'subcat.plants': 'Plants',
    'delivery.meetup': 'Meetup Only',
    'delivery.shipping': 'Shipping Only',
    'delivery.both': 'Meetup & Shipping',
    'detail.back': 'Back',
    'detail.seller': 'Seller',
    'detail.verified': 'Verified Seller',
    'detail.contact': 'Chat with Seller',
    'detail.posted': 'Posted',
    'detail.location': 'Location',
    'detail.delivery': 'Delivery',
    'detail.desc_title': 'Description',
    'detail.recommend': 'Recommended',
    'detail.report': 'Report this listing',
    'profile.title': 'My Profile',
    'profile.avatar': 'Avatar',
    'profile.change_avatar': 'Change Photo',
    'profile.name': 'Name',
    'profile.email': 'Email',
    'profile.save': 'Save Changes',
    'profile.saved': 'Saved!',
    'profile.listings': 'My Listings',
    'profile.no_listings': 'No active listings',
    'profile.verify_title': 'Identity Verification',
    'profile.verify_desc': 'Upload your ID to become a trusted seller and boost sales.',
    'profile.get_verified': 'Submit ID (Free)',
    'profile.verifying': 'Uploading...',
    'profile.is_verified': 'Identity Verified',
    'profile.boost': 'Boost',
    'profile.safety_policies': 'Safety & Policies',
    'profile.content_policy': 'Content & Political Norms',
    'profile.privacy_policy': 'Privacy Policy',
    'profile.buying': 'My Orders',
    'profile.selling': 'Sales',
    'profile.payouts': 'Payouts & Earnings',
    'profile.payouts_desc': 'Connect your bank account to receive payments directly just like a professional store.',
    'profile.setup_payouts': 'Setup Payouts',
    'report.title': 'Report Content',
    'report.reason': 'Reason for reporting',
    'report.reason.misinfo': 'Political Misinformation',
    'report.reason.hate': 'Hate Speech or Discrimination',
    'report.reason.scam': 'Scam or Misleading',
    'report.reason.prohibited': 'Prohibited Item',
    'report.reason.sensitive': 'Sensitive Political Content',
    'report.submit': 'Submit Report',
    'report.success': 'Thank you for your report. We will review it shortly.',
    'time.today': 'Today',
    'time.days_ago': '{0} days ago',
    'chat.inbox': 'Messages',
    'chat.type': 'Type a message...',
    'chat.send': 'Send',
    'chat.no_msgs': 'No messages yet',
    'chat.empty_inbox': 'No conversations yet',
    'chat.you': 'You',
    // Negotiation
    'nego.title': 'Offer',
    'nego.original_price': 'Original',
    'nego.your_offer': 'Your Offer',
    'nego.counter_price': 'Seller Offer',
    'nego.final_price': 'Final Price',
    'nego.status.pending': 'Pending',
    'nego.status.accepted': 'Accepted',
    'nego.status.rejected': 'Rejected',
    'nego.status.countered': 'Counter Offered',
    'nego.action.accept': 'Accept',
    'nego.action.counter': 'Counter',
    'nego.action.reject': 'Reject',
    'nego.confirm_counter': 'Confirm Counter',
    'nego.cancel': 'Cancel',
    'nego.success.accepted': 'Deal! Price',
    'nego.success.rejected': 'Seller rejected this offer',
    'nego.success.countered': 'Seller made a counter offer',
    'nego.enter_price': 'Enter your price',
    'nego.failed': 'Failed to respond, please retry',
    // Chat tabs
    'chat.tab.all': 'All',
    'chat.tab.active': 'Active',
    'chat.tab.inquiring': 'Inquiring',
    'chat.tab.completed': 'Completed',
    'chat.unknown_product': 'Unknown Product',
    'chat.view_details': 'Click to view details',
    'chat.conversations': 'conversations',
    'chat.empty_inbox_hint': 'Start a conversation from a product page',
    'chat.no_chats_in_tab': 'No conversations in this category',
    'chat.buyers': 'buyers',
    'chat.hide': 'Hide',
    'chat.delete': 'Delete',
    'chat.trading': 'Trading',
    'chat.hide_conversation': 'Hide Chat',
    'chat.delete_conversation': 'Delete Chat',
    'chat.delete_confirm': 'Delete this chat? This cannot be undone.',
    'chat.hidden_count': 'chats hidden',
    'chat.online': 'Online',
    'chat.view_product': 'Tap to view details',
    'chat.report_user': 'Report User',
    'chat.block_user': 'Block User',
    'chat.user_reported': 'User reported',
    'chat.user_blocked': 'User blocked',
    'chat.loading': 'Loading...',
    'chat.load_earlier': 'Load earlier messages',
    'chat.send_failed': 'Send failed, please retry',
    'chat.make_offer': 'Make Offer',
    'chat.share_location': 'Share Location',
    'chat.arrange_meetup': 'Arrange Meetup',
    'chat.arrange_meetup_btn': 'Arrange Meetup',
    'chat.deleted_success': 'Chat deleted',
    'list.search_hint': 'Try different keywords or broader terms',
    'list.empty_hint': 'Be the first to list an item in this category!',
    'product.rate_seller': 'Rate Seller',
    'product.share': 'Share',
    'profile.reviews': 'Reviews',
    'nav.logout': 'Log Out',
    // Toast Messages
    'toast.login_failed': 'Login verification failed',
    'toast.profile_updated': 'Profile updated successfully',
    'toast.update_failed': 'Update failed',
    'toast.product_published': '🎉 Product published successfully!',
    'toast.product_publish_failed': '❌ Failed to publish product',
    'toast.please_login': 'Please log in first',
    'toast.favorite_added': 'Added to favorites',
    'toast.favorite_removed': 'Removed from favorites',
    'toast.favorite_update_failed': 'Failed to update favorite',
    'toast.chat_open_failed': '❌ Unable to open chat, please try again',
    'toast.message_send_failed': '❌ Failed to send message, please retry',
    'toast.load_failed': 'Failed to load',
    'toast.upload_failed': 'Upload failed, please try again',
  },
  es: {
    'app.name': 'DESCU',
    'nav.search': 'Buscar autos, depas, servicios...',
    'nav.sell': 'Vender',
    'nav.home': 'Inicio',
    'nav.cart': 'Carrito',
    'nav.favorites': 'Favoritos',
    'nav.profile': 'Perfil',
    'nav.login': 'Entrar',
    'nav.chat': 'Mensajes',
    'nav.notifications': 'Alertas',
    'login.required': 'Iniciar Sesión',
    'login.prompt': 'Por favor inicia sesión para continuar',
    'login.google': 'Continuar con Google',
    'login.terms': 'Al continuar, aceptas nuestros Términos',
    'hero.title': 'Compra local, vende rápido',
    'hero.subtitle': 'Tu mercado digital inteligente.',
    'hero.cta': 'Ver Ofertas',
    'list.header': 'Recomendados',
    'list.search_results': 'Resultados',
    'list.items_count': 'artículos',
    'list.loading_loc': 'Ubicando...',
    'list.loc_denied': 'Activar Ubicación',
    'list.loc_success': 'Cerca de ti',
    'list.empty': '¡Sé el primero en vender algo!',
    'list.no_results': 'No se encontraron resultados',
    'list.view_all': 'Ver Todo',
    'list.load_more': 'Cargar Más',
    'list.loading_more': 'Cargando...',
    'card.nearby': 'Cerca',
    'chat.ask_price': 'Ofertar',
    'chat.offer_title': 'Hacer Oferta',
    'chat.current_price': 'Precio Actual',
    'chat.your_offer': 'Tu Oferta',
    'chat.send_offer': 'Enviar Oferta',
    'chat.cancel': 'Cancelar',
    'card.add_cart': 'Lo quiero',
    'card.in_cart': 'Agregado',
    'card.promoted': 'Destacado',
    'modal.title': 'Publicar Anuncio',
    'modal.upload_text': 'Subir Foto',
    'modal.upload_hint': 'La IA llenará los datos por ti',
    'modal.change_img': 'Cambiar Foto',
    'modal.analyzing': 'IA analizando imagen...',
    'modal.analyzed': 'Datos generados por IA',
    'modal.label.title': 'Título',
    'modal.ph.title': 'ej. VW Jetta 2018 impecable',
    'modal.label.price': 'Precio',
    'modal.label.category': 'Categoría',
    'modal.label.delivery': 'Entrega',
    'modal.label.desc': 'Descripción',
    'modal.ph.desc': 'Detalles, condiciones, kilometraje...',
    'modal.loc.loading': 'Localizando...',
    'modal.loc.success': 'Ubicación agregada',
    'modal.submit': 'Publicar Ahora',
    'modal.submit.analyzing': 'Analizando...',
    'modal.policy_hint': 'Al publicar, aceptas nuestras políticas. Se prohíbe el discurso de odio y la desinformación política.',
    'modal.ai_error': 'Análisis de IA fallido. Revisa tu conexión o intenta más tarde.',
    'cart.title': 'Carrito',
    'cart.empty': 'Tu carrito está vacío',
    'cart.go_shop': 'Ir a la tienda',
    'cart.total': 'Total',
    'cart.checkout': 'Comprar',
    'cart.processing': 'Procesando...',
    'cart.success': '¡Compra exitosa!',
    'cat.all': 'Todo',
    'cat.electronics': 'Electrónica',
    'cat.furniture': 'Hogar',
    'cat.clothing': 'Moda',
    'cat.books': 'Libros',
    'cat.sports': 'Deportes',
    'cat.vehicles': 'Autos',
    'cat.real_estate': 'Inmuebles',
    'cat.services': 'Servicios',
    'cat.other': 'Otros',
    // Subcategories - Electronics
    'subcat.phones': 'Celulares',
    'subcat.laptops': 'Laptops',
    'subcat.tablets': 'Tablets',
    'subcat.cameras': 'Cámaras',
    'subcat.audio': 'Audio',
    'subcat.gaming': 'Gaming',
    'subcat.wearables': 'Wearables',
    'subcat.accessories': 'Accesorios',
    // Subcategories - Vehicles
    'subcat.cars': 'Autos',
    'subcat.motorcycles': 'Motos',
    'subcat.bicycles': 'Bicicletas',
    'subcat.trucks': 'Camiones',
    'subcat.parts': 'Refacciones',
    // Subcategories - RealEstate
    'subcat.apartments': 'Departamentos',
    'subcat.houses': 'Casas',
    'subcat.land': 'Terrenos',
    'subcat.commercial': 'Locales',
    'subcat.rentals': 'Renta',
    // Subcategories - Furniture
    'subcat.sofas': 'Sofás',
    'subcat.beds': 'Camas',
    'subcat.tables': 'Mesas y Sillas',
    'subcat.storage': 'Almacenaje',
    'subcat.office': 'Muebles de Oficina',
    // Subcategories - Clothing
    'subcat.women': 'Mujer',
    'subcat.men': 'Hombre',
    'subcat.kids': 'Niños',
    'subcat.shoes': 'Zapatos',
    'subcat.fashion_accessories': 'Accesorios de Moda',
    // Subcategories - Sports
    'subcat.fitness': 'Fitness',
    'subcat.outdoor': 'Exterior',
    'subcat.team_sports': 'Deportes de Equipo',
    'subcat.water_sports': 'Deportes Acuáticos',
    'subcat.winter_sports': 'Deportes de Invierno',
    // Subcategories - Services
    'subcat.repair': 'Reparación',
    'subcat.cleaning': 'Limpieza',
    'subcat.teaching': 'Clases',
    'subcat.beauty': 'Belleza',
    'subcat.moving': 'Mudanzas',
    // Subcategories - Books
    'subcat.fiction': 'Ficción',
    'subcat.textbooks': 'Libros de Texto',
    'subcat.children': 'Infantil',
    'subcat.magazines': 'Revistas',
    'subcat.comics': 'Cómics',
    // Subcategories - Other
    'subcat.collectibles': 'Coleccionables',
    'subcat.pets': 'Mascotas',
    'subcat.food': 'Comida',
    'subcat.plants': 'Plantas',
    'delivery.meetup': 'Entrega Personal',
    'delivery.shipping': 'Envío a Domicilio',
    'delivery.both': 'Entrega Personal o Envío',
    'detail.back': 'Volver',
    'detail.seller': 'Vendedor',
    'detail.verified': 'Vendedor Verificado',
    'detail.contact': 'Contactar Vendedor',
    'detail.posted': 'Publicado',
    'detail.location': 'Ubicación',
    'detail.delivery': 'Entrega',
    'detail.desc_title': 'Descripción',
    'detail.recommend': 'Te puede interesar',
    'detail.report': 'Reportar este anuncio',
    'profile.title': 'Mi Perfil',
    'profile.avatar': 'Foto de Perfil',
    'profile.change_avatar': 'Cambiar Foto',
    'profile.name': 'Nombre',
    'profile.email': 'Correo',
    'profile.save': 'Guardar Cambios',
    'profile.saved': '¡Guardado!',
    'profile.listings': 'Mis Publicaciones',
    'profile.no_listings': 'Sin publicaciones activas',
    'profile.verify_title': 'Verificación de Identidad',
    'profile.verify_desc': 'Sube tu identificación oficial (INE/Pasaporte) para ser un vendedor confiable.',
    'profile.get_verified': 'Subir ID (Gratis)',
    'profile.verifying': 'Subiendo...',
    'profile.is_verified': 'Identidad Verificada',
    'profile.boost': 'Destacar',
    'profile.safety_policies': 'Seguridad y Políticas',
    'profile.content_policy': 'Normas de Contenido y Política',
    'profile.privacy_policy': 'Política de Privacidad',
    'profile.buying': 'Mis Compras',
    'profile.selling': 'Mis Ventas',
    'profile.payouts': 'Pagos y Ganancias',
    'profile.payouts_desc': 'Conecta tu cuenta bancaria para recibir pagos directamente como una tienda profesional.',
    'profile.setup_payouts': 'Configurar Pagos',
    'report.title': 'Reportar Contenido',
    'report.reason': 'Motivo del reporte',
    'report.reason.misinfo': 'Desinformación Política',
    'report.reason.hate': 'Discurso de Odio o Discriminación',
    'report.reason.scam': 'Fraude o Engaño',
    'report.reason.prohibited': 'Artículo Prohibido',
    'report.reason.sensitive': 'Contenido Político Sensible',
    'report.submit': 'Enviar Reporte',
    'report.success': 'Gracias por tu reporte. Lo revisaremos a la brevedad.',
    'time.today': 'Hoy',
    'time.days_ago': 'Hace {0} días',
    'chat.inbox': 'Mensajes',
    'chat.type': 'Escribe un mensaje...',
    'chat.send': 'Enviar',
    'chat.no_msgs': 'Aún no hay mensajes',
    'chat.empty_inbox': 'No tienes conversaciones',
    'chat.you': 'Tú',
    // Negociación
    'nego.title': 'Oferta',
    'nego.original_price': 'Precio Original',
    'nego.your_offer': 'Tu Oferta',
    'nego.counter_price': 'Contraoferta',
    'nego.final_price': 'Precio Final',
    'nego.status.pending': 'Pendiente',
    'nego.status.accepted': 'Aceptada',
    'nego.status.rejected': 'Rechazada',
    'nego.status.countered': 'Contraoferta',
    'nego.action.accept': 'Aceptar',
    'nego.action.counter': 'Contraofertar',
    'nego.action.reject': 'Rechazar',
    'nego.confirm_counter': 'Confirmar',
    'nego.cancel': 'Cancelar',
    'nego.success.accepted': '¡Trato hecho! Precio',
    'nego.success.rejected': 'El vendedor rechazó esta oferta',
    'nego.success.countered': 'El vendedor hizo una contraoferta',
    'nego.enter_price': 'Ingresa tu precio',
    'nego.failed': 'Error al responder, intenta de nuevo',
    // Pestañas de chat
    'chat.tab.all': 'Todo',
    'chat.tab.active': 'Activo',
    'chat.tab.inquiring': 'Consultando',
    'chat.tab.completed': 'Completado',
    'chat.unknown_product': 'Producto desconocido',
    'chat.view_details': 'Clic para ver detalles',
    'chat.conversations': 'conversaciones',
    'chat.empty_inbox_hint': 'Inicia una conversación desde un producto',
    'chat.no_chats_in_tab': 'No hay conversaciones en esta categoría',
    'chat.buyers': 'compradores',
    'chat.hide': 'Ocultar',
    'chat.delete': 'Eliminar',
    'chat.trading': 'En proceso',
    'chat.hide_conversation': 'Ocultar chat',
    'chat.delete_conversation': 'Eliminar chat',
    'chat.delete_confirm': '¿Eliminar este chat? Esta acción no se puede deshacer.',
    'chat.hidden_count': 'chats ocultos',
    'chat.online': 'En línea',
    'chat.view_product': 'Toca para ver detalles',
    'chat.report_user': 'Reportar Usuario',
    'chat.block_user': 'Bloquear Usuario',
    'chat.user_reported': 'Usuario reportado',
    'chat.user_blocked': 'Usuario bloqueado',
    'chat.loading': 'Cargando...',
    'chat.load_earlier': 'Cargar mensajes anteriores',
    'chat.send_failed': 'Envío fallido, intenta de nuevo',
    'chat.make_offer': 'Ofertar',
    'chat.share_location': 'Compartir Ubicación',
    'chat.arrange_meetup': 'Agendar Encuentro',
    'chat.arrange_meetup_btn': 'Agendar Encuentro',
    'chat.deleted_success': 'Chat eliminado',
    'list.search_hint': 'Intenta con otras palabras o términos más amplios',
    'list.empty_hint': '¡Sé el primero en publicar en esta categoría!',
    'product.rate_seller': 'Calificar Vendedor',
    'product.share': 'Compartir',
    'profile.reviews': 'Reseñas',
    'nav.logout': 'Cerrar Sesión',
    // Mensajes Toast
    'toast.login_failed': 'Error de verificación de inicio de sesión',
    'toast.profile_updated': 'Perfil actualizado exitosamente',
    'toast.update_failed': 'Actualización fallida',
    'toast.product_published': '🎉 ¡Producto publicado con éxito!',
    'toast.product_publish_failed': '❌ Error al publicar producto',
    'toast.please_login': 'Por favor inicia sesión primero',
    'toast.favorite_added': 'Agregado a favoritos',
    'toast.favorite_removed': 'Eliminado de favoritos',
    'toast.favorite_update_failed': 'Error al actualizar favorito',
    'toast.chat_open_failed': '❌ No se puede abrir el chat, intenta más tarde',
    'toast.message_send_failed': '❌ Error al enviar mensaje, intenta de nuevo',
    'toast.load_failed': 'Error al cargar',
    'toast.upload_failed': 'Error al subir, intenta de nuevo',
  }
};

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>(() => {
    // 1. Check local storage
    const saved = localStorage.getItem('app_language') as Language;
    if (saved && ['zh', 'en', 'es'].includes(saved)) return saved;

    // 2. Check browser language
    if (typeof navigator !== 'undefined') {
      const browserLang = navigator.language.toLowerCase();
      if (browserLang.startsWith('zh')) return 'zh';
      if (browserLang.startsWith('en')) return 'en';
      if (browserLang.startsWith('es')) return 'es';
    }

    // 3. Default
    return 'es';
  });

  useEffect(() => {
    localStorage.setItem('app_language', language);
  }, [language]);

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  const formatPrice = (price: number) => {
    if (language === 'zh') {
      return `¥${price.toLocaleString()}`;
    } else {
      return `$${price.toLocaleString()}`;
    }
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, formatPrice }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
