
import React, { createContext, useContext, useState, useEffect, ReactNode } from 'react';
import { Language } from '../types';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
  formatPrice: (price: number) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations: Record<Language, Record<string, string>> = {
  zh: {
    'app.name': 'DESCU',
    'nav.search': '搜索宝贝、车辆、房产...',
    'nav.sell': '卖闲置',
    'nav.home': '首页',
    'nav.cart': '购物车',
    'nav.favorites': '我的收藏',
    'nav.profile': '我的',
    'nav.login': '登录',
    'nav.chat': '消息',
    'hero.title': '本地买卖，方便快捷',
    'hero.subtitle': '您身边的AI智能二手平台',
    'hero.cta': '立即探索',
    'list.header': '为您推荐',
    'list.search_results': '搜索结果',
    'list.items_count': '件商品',
    'list.loading_loc': '正在定位...',
    'list.loc_denied': '请开启定位',
    'list.loc_success': '附近',
    'list.empty': '暂无商品，快来发布第一个吧！',
    'list.no_results': '没有找到相关商品',
    'list.view_all': '查看所有商品',
    'list.load_more': '加载更多',
    'list.loading_more': '加载中...',
    'card.nearby': '附近',
    'chat.ask_price': '议价',
    'chat.offer_title': '提出议价',
    'chat.current_price': '当前价格',
    'chat.your_offer': '您的出价',
    'chat.send_offer': '发送议价',
    'chat.cancel': '取消',
    'card.add_cart': '想要',
    'card.in_cart': '已添加',
    'card.promoted': '推广',
    'modal.title': '发布闲置',
    'modal.upload_text': '点击上传照片',
    'modal.upload_hint': 'AI将自动识别并填写信息',
    'modal.change_img': '更改图片',
    'modal.analyzing': 'AI 正在分析图片生成描述...',
    'modal.analyzed': 'AI 已为您自动填充信息',
    'modal.label.title': '标题',
    'modal.ph.title': '例如：95成新 iPhone 14',
    'modal.label.price': '价格',
    'modal.label.category': '分类',
    'modal.label.delivery': '交易方式',
    'modal.label.desc': '详细描述',
    'modal.ph.desc': '描述一下物品的新旧程度、入手渠道等...',
    'modal.loc.loading': '定位中...',
    'modal.loc.success': '位置已锁定',
    'modal.submit': '立即发布',
    'modal.submit.analyzing': '分析中...',
    'modal.policy_hint': '发布即表示您同意我们的内容政策，严禁发布仇恨言论或虚假政治信息。',
    'modal.ai_error': 'AI分析失败，请检查网络或稍后重试',
    'cart.title': '购物车',
    'cart.empty': '购物车空空如也',
    'cart.go_shop': '去逛逛',
    'cart.total': '合计',
    'cart.checkout': '立即结算',
    'cart.processing': '处理中...',
    'cart.success': '下单成功！',
    'cat.all': '全部',
    'cat.electronics': '数码',
    'cat.furniture': '家具',
    'cat.clothing': '服饰',
    'cat.books': '图书',
    'cat.sports': '运动',
    'cat.vehicles': '车辆',
    'cat.real_estate': '房产',
    'cat.services': '服务',
    'cat.other': '其他',
    'delivery.meetup': '当面交易',
    'delivery.shipping': '快递发货',
    'delivery.both': '面交/快递',
    'detail.back': '返回',
    'detail.seller': '卖家信息',
    'detail.verified': '已认证卖家',
    'detail.contact': '联系卖家',
    'detail.posted': '发布于',
    'detail.location': '交易地点',
    'detail.delivery': '配送方式',
    'detail.desc_title': '商品详情',
    'detail.recommend': '猜你喜欢',
    'detail.report': '举报此内容',
    'profile.title': '个人中心',
    'profile.avatar': '头像',
    'profile.change_avatar': '更换头像',
    'profile.name': '昵称',
    'profile.email': '邮箱',
    'profile.save': '保存修改',
    'profile.saved': '保存成功！',
    'profile.listings': '我发布的',
    'profile.no_listings': '暂无发布记录',
    'profile.verify_title': '身份认证',
    'profile.verify_desc': '提交身份证件，获得蓝盾标识，做值得信赖的卖家。',
    'profile.get_verified': '提交证件 (免费)',
    'profile.verifying': '审核中...',
    'profile.is_verified': '身份已认证',
    'profile.boost': '推广',
    'profile.safety_policies': '安全与政策',
    'profile.content_policy': '内容与政治规范',
    'profile.buying': '我的订单',
    'profile.selling': '我的销售',
    'profile.payouts': '收款设置',
    'profile.payouts_desc': '绑定银行账户以接收销售款项 (支持Stripe)。',
    'profile.setup_payouts': '立即绑定',
    'report.title': '举报内容',
    'report.reason': '举报原因',
    'report.reason.misinfo': '政治虚假信息',
    'report.reason.hate': '仇恨言论或歧视',
    'report.reason.scam': '诈骗或误导',
    'report.reason.prohibited': '禁止销售的物品',
    'report.reason.sensitive': '敏感政治宣传',
    'report.submit': '提交举报',
    'report.success': '感谢您的反馈，我们将进行审核。',
    'time.today': '今天',
    'time.days_ago': '{0}天前',
    'chat.inbox': '消息列表',
    'chat.type': '输入消息...',
    'chat.send': '发送',
    'chat.no_msgs': '暂无消息',
    'chat.empty_inbox': '还没有开始任何对话',
    'chat.you': '你',
    // 议价相关
    'nego.title': '议价',
    'nego.original_price': '原价',
    'nego.your_offer': '出价',
    'nego.counter_price': '卖家报价',
    'nego.final_price': '成交价',
    'nego.status.pending': '待响应',
    'nego.status.accepted': '已接受',
    'nego.status.rejected': '已拒绝',
    'nego.status.countered': '卖家还价',
    'nego.action.accept': '接受',
    'nego.action.counter': '还价',
    'nego.action.reject': '拒绝',
    'nego.confirm_counter': '确认还价',
    'nego.cancel': '取消',
    'nego.success.accepted': '议价成功！价格',
    'nego.success.rejected': '卖家拒绝了此议价',
    'nego.success.countered': '卖家提出新报价',
    'nego.enter_price': '输入您的报价',
    'nego.failed': '响应议价失败，请重试',
    // 聊天列表
    'chat.tab.all': '全部',
    'chat.tab.active': '进行中',
    'chat.tab.inquiring': '咨询中',
    'chat.tab.completed': '已完成',
    'chat.unknown_product': '未知商品',
    'chat.view_details': '点击查看详情 / Ver detalles',
  },
  en: {
    'app.name': 'DESCU',
    'nav.search': 'Search items, cars, homes...',
    'nav.sell': 'Sell',
    'nav.home': 'Home',
    'nav.cart': 'Cart',
    'nav.favorites': 'Favorites',
    'nav.profile': 'Profile',
    'nav.login': 'Login',
    'nav.chat': 'Chat',
    'hero.title': 'Buy Local, Sell in a Flash',
    'hero.subtitle': 'Your AI-powered neighborhood marketplace. Find hidden gems within 5km.',
    'hero.cta': 'Explore Now',
    'list.header': 'Recommended for You',
    'list.search_results': 'Search Results',
    'list.items_count': 'items',
    'list.loading_loc': 'Locating...',
    'list.loc_denied': 'Enable Location',
    'list.loc_success': 'Nearby',
    'list.empty': 'No items yet. Be the first to sell!',
    'list.no_results': 'No items found',
    'list.view_all': 'View All',
    'list.load_more': 'Load More',
    'list.loading_more': 'Loading...',
    'card.nearby': 'Nearby',
    'chat.ask_price': 'Make Offer',
    'chat.offer_title': 'Make an Offer',
    'chat.current_price': 'Current Price',
    'chat.your_offer': 'Your Offer',
    'chat.send_offer': 'Send Offer',
    'chat.cancel': 'Cancel',
    'card.add_cart': 'Add',
    'card.in_cart': 'Added',
    'card.promoted': 'Promoted',
    'modal.title': 'List Item',
    'modal.upload_text': 'Upload Photo',
    'modal.upload_hint': 'AI will auto-fill details',
    'modal.change_img': 'Change Photo',
    'modal.analyzing': 'AI analyzing...',
    'modal.analyzed': 'AI details generated',
    'modal.label.title': 'Title',
    'modal.ph.title': 'e.g., Like new iPhone 14',
    'modal.label.price': 'Price',
    'modal.label.category': 'Category',
    'modal.label.delivery': 'Delivery Method',
    'modal.label.desc': 'Description',
    'modal.ph.desc': 'Describe condition, usage, etc...',
    'modal.loc.loading': 'Locating...',
    'modal.loc.success': 'Location Locked',
    'modal.submit': 'Post Listing',
    'modal.submit.analyzing': 'Analyzing...',
    'modal.policy_hint': 'By posting, you agree to our policies. Hate speech and political misinformation are strictly prohibited.',
    'modal.ai_error': 'AI analysis failed. Please check connection or try again.',
    'cart.title': 'Cart',
    'cart.empty': 'Your cart is empty',
    'cart.go_shop': 'Go Shopping',
    'cart.total': 'Total',
    'cart.checkout': 'Checkout',
    'cart.processing': 'Processing...',
    'cart.success': 'Order Placed!',
    'cat.all': 'All',
    'cat.electronics': 'Electronics',
    'cat.furniture': 'Furniture',
    'cat.clothing': 'Clothing',
    'cat.books': 'Books',
    'cat.sports': 'Sports',
    'cat.vehicles': 'Vehicles',
    'cat.real_estate': 'Real Estate',
    'cat.services': 'Services',
    'cat.other': 'Other',
    'delivery.meetup': 'Meetup Only',
    'delivery.shipping': 'Shipping Only',
    'delivery.both': 'Meetup & Shipping',
    'detail.back': 'Back',
    'detail.seller': 'Seller',
    'detail.verified': 'Verified Seller',
    'detail.contact': 'Chat with Seller',
    'detail.posted': 'Posted',
    'detail.location': 'Location',
    'detail.delivery': 'Delivery',
    'detail.desc_title': 'Description',
    'detail.recommend': 'Recommended',
    'detail.report': 'Report this listing',
    'profile.title': 'My Profile',
    'profile.avatar': 'Avatar',
    'profile.change_avatar': 'Change Photo',
    'profile.name': 'Name',
    'profile.email': 'Email',
    'profile.save': 'Save Changes',
    'profile.saved': 'Saved!',
    'profile.listings': 'My Listings',
    'profile.no_listings': 'No active listings',
    'profile.verify_title': 'Identity Verification',
    'profile.verify_desc': 'Upload your ID to become a trusted seller and boost sales.',
    'profile.get_verified': 'Submit ID (Free)',
    'profile.verifying': 'Uploading...',
    'profile.is_verified': 'Identity Verified',
    'profile.boost': 'Boost',
    'profile.safety_policies': 'Safety & Policies',
    'profile.content_policy': 'Content & Political Norms',
    'profile.buying': 'My Orders',
    'profile.selling': 'Sales',
    'profile.payouts': 'Payouts & Earnings',
    'profile.payouts_desc': 'Connect your bank account to receive payments directly just like a professional store.',
    'profile.setup_payouts': 'Setup Payouts',
    'report.title': 'Report Content',
    'report.reason': 'Reason for reporting',
    'report.reason.misinfo': 'Political Misinformation',
    'report.reason.hate': 'Hate Speech or Discrimination',
    'report.reason.scam': 'Scam or Misleading',
    'report.reason.prohibited': 'Prohibited Item',
    'report.reason.sensitive': 'Sensitive Political Content',
    'report.submit': 'Submit Report',
    'report.success': 'Thank you for your report. We will review it shortly.',
    'time.today': 'Today',
    'time.days_ago': '{0} days ago',
    'chat.inbox': 'Messages',
    'chat.type': 'Type a message...',
    'chat.send': 'Send',
    'chat.no_msgs': 'No messages yet',
    'chat.empty_inbox': 'No conversations yet',
    'chat.you': 'You',
    // Negotiation
    'nego.title': 'Offer',
    'nego.original_price': 'Original',
    'nego.your_offer': 'Your Offer',
    'nego.counter_price': 'Seller Offer',
    'nego.final_price': 'Final Price',
    'nego.status.pending': 'Pending',
    'nego.status.accepted': 'Accepted',
    'nego.status.rejected': 'Rejected',
    'nego.status.countered': 'Counter Offered',
    'nego.action.accept': 'Accept',
    'nego.action.counter': 'Counter',
    'nego.action.reject': 'Reject',
    'nego.confirm_counter': 'Confirm Counter',
    'nego.cancel': 'Cancel',
    'nego.success.accepted': 'Deal! Price',
    'nego.success.rejected': 'Seller rejected this offer',
    'nego.success.countered': 'Seller made a counter offer',
    'nego.enter_price': 'Enter your price',
    'nego.failed': 'Failed to respond, please retry',
    // Chat tabs
    'chat.tab.all': 'All',
    'chat.tab.active': 'Active',
    'chat.tab.inquiring': 'Inquiring',
    'chat.tab.completed': 'Completed',
    'chat.unknown_product': 'Unknown Product',
    'chat.view_details': 'Click to view details',
  },
  es: {
    'app.name': 'DESCU',
    'nav.search': 'Buscar autos, depas, servicios...',
    'nav.sell': 'Vender',
    'nav.home': 'Inicio',
    'nav.cart': 'Carrito',
    'nav.favorites': 'Favoritos',
    'nav.profile': 'Perfil',
    'nav.login': 'Entrar',
    'nav.chat': 'Mensajes',
    'hero.title': 'Compra local, vende rápido',
    'hero.subtitle': 'Tu mercado digital inteligente.',
    'hero.cta': 'Ver Ofertas',
    'list.header': 'Recomendados',
    'list.search_results': 'Resultados',
    'list.items_count': 'artículos',
    'list.loading_loc': 'Ubicando...',
    'list.loc_denied': 'Activar Ubicación',
    'list.loc_success': 'Cerca de ti',
    'list.empty': '¡Sé el primero en vender algo!',
    'list.no_results': 'No se encontraron resultados',
    'list.view_all': 'Ver Todo',
    'list.load_more': 'Cargar Más',
    'list.loading_more': 'Cargando...',
    'card.nearby': 'Cerca',
    'chat.ask_price': 'Ofertar',
    'chat.offer_title': 'Hacer Oferta',
    'chat.current_price': 'Precio Actual',
    'chat.your_offer': 'Tu Oferta',
    'chat.send_offer': 'Enviar Oferta',
    'chat.cancel': 'Cancelar',
    'card.add_cart': 'Lo quiero',
    'card.in_cart': 'Agregado',
    'card.promoted': 'Destacado',
    'modal.title': 'Publicar Anuncio',
    'modal.upload_text': 'Subir Foto',
    'modal.upload_hint': 'La IA llenará los datos por ti',
    'modal.change_img': 'Cambiar Foto',
    'modal.analyzing': 'IA analizando imagen...',
    'modal.analyzed': 'Datos generados por IA',
    'modal.label.title': 'Título',
    'modal.ph.title': 'ej. VW Jetta 2018 impecable',
    'modal.label.price': 'Precio',
    'modal.label.category': 'Categoría',
    'modal.label.delivery': 'Entrega',
    'modal.label.desc': 'Descripción',
    'modal.ph.desc': 'Detalles, condiciones, kilometraje...',
    'modal.loc.loading': 'Localizando...',
    'modal.loc.success': 'Ubicación agregada',
    'modal.submit': 'Publicar Ahora',
    'modal.submit.analyzing': 'Analizando...',
    'modal.policy_hint': 'Al publicar, aceptas nuestras políticas. Se prohíbe el discurso de odio y la desinformación política.',
    'modal.ai_error': 'Análisis de IA fallido. Revisa tu conexión o intenta más tarde.',
    'cart.title': 'Carrito',
    'cart.empty': 'Tu carrito está vacío',
    'cart.go_shop': 'Ir a la tienda',
    'cart.total': 'Total',
    'cart.checkout': 'Comprar',
    'cart.processing': 'Procesando...',
    'cart.success': '¡Compra exitosa!',
    'cat.all': 'Todo',
    'cat.electronics': 'Electrónica',
    'cat.furniture': 'Hogar',
    'cat.clothing': 'Moda',
    'cat.books': 'Libros',
    'cat.sports': 'Deportes',
    'cat.vehicles': 'Autos',
    'cat.real_estate': 'Inmuebles',
    'cat.services': 'Servicios',
    'cat.other': 'Otros',
    'delivery.meetup': 'Entrega Personal',
    'delivery.shipping': 'Envío a Domicilio',
    'delivery.both': 'Entrega Personal o Envío',
    'detail.back': 'Volver',
    'detail.seller': 'Vendedor',
    'detail.verified': 'Vendedor Verificado',
    'detail.contact': 'Contactar Vendedor',
    'detail.posted': 'Publicado',
    'detail.location': 'Ubicación',
    'detail.delivery': 'Entrega',
    'detail.desc_title': 'Descripción',
    'detail.recommend': 'Te puede interesar',
    'detail.report': 'Reportar este anuncio',
    'profile.title': 'Mi Perfil',
    'profile.avatar': 'Foto de Perfil',
    'profile.change_avatar': 'Cambiar Foto',
    'profile.name': 'Nombre',
    'profile.email': 'Correo',
    'profile.save': 'Guardar Cambios',
    'profile.saved': '¡Guardado!',
    'profile.listings': 'Mis Publicaciones',
    'profile.no_listings': 'Sin publicaciones activas',
    'profile.verify_title': 'Verificación de Identidad',
    'profile.verify_desc': 'Sube tu identificación oficial (INE/Pasaporte) para ser un vendedor confiable.',
    'profile.get_verified': 'Subir ID (Gratis)',
    'profile.verifying': 'Subiendo...',
    'profile.is_verified': 'Identidad Verificada',
    'profile.boost': 'Destacar',
    'profile.safety_policies': 'Seguridad y Políticas',
    'profile.content_policy': 'Normas de Contenido y Política',
    'profile.buying': 'Mis Compras',
    'profile.selling': 'Mis Ventas',
    'profile.payouts': 'Pagos y Ganancias',
    'profile.payouts_desc': 'Conecta tu cuenta bancaria para recibir pagos directamente como una tienda profesional.',
    'profile.setup_payouts': 'Configurar Pagos',
    'report.title': 'Reportar Contenido',
    'report.reason': 'Motivo del reporte',
    'report.reason.misinfo': 'Desinformación Política',
    'report.reason.hate': 'Discurso de Odio o Discriminación',
    'report.reason.scam': 'Fraude o Engaño',
    'report.reason.prohibited': 'Artículo Prohibido',
    'report.reason.sensitive': 'Contenido Político Sensible',
    'report.submit': 'Enviar Reporte',
    'report.success': 'Gracias por tu reporte. Lo revisaremos a la brevedad.',
    'time.today': 'Hoy',
    'time.days_ago': 'Hace {0} días',
    'chat.inbox': 'Mensajes',
    'chat.type': 'Escribe un mensaje...',
    'chat.send': 'Enviar',
    'chat.no_msgs': 'Aún no hay mensajes',
    'chat.empty_inbox': 'No tienes conversaciones',
    'chat.you': 'Tú',
    // Negociación
    'nego.title': 'Oferta',
    'nego.original_price': 'Precio Original',
    'nego.your_offer': 'Tu Oferta',
    'nego.counter_price': 'Contraoferta',
    'nego.final_price': 'Precio Final',
    'nego.status.pending': 'Pendiente',
    'nego.status.accepted': 'Aceptada',
    'nego.status.rejected': 'Rechazada',
    'nego.status.countered': 'Contraoferta',
    'nego.action.accept': 'Aceptar',
    'nego.action.counter': 'Contraofertar',
    'nego.action.reject': 'Rechazar',
    'nego.confirm_counter': 'Confirmar',
    'nego.cancel': 'Cancelar',
    'nego.success.accepted': '¡Trato hecho! Precio',
    'nego.success.rejected': 'El vendedor rechazó esta oferta',
    'nego.success.countered': 'El vendedor hizo una contraoferta',
    'nego.enter_price': 'Ingresa tu precio',
    'nego.failed': 'Error al responder, intenta de nuevo',
    // Pestañas de chat
    'chat.tab.all': 'Todo',
    'chat.tab.active': 'Activo',
    'chat.tab.inquiring': 'Consultando',
    'chat.tab.completed': 'Completado',
    'chat.unknown_product': 'Producto desconocido',
    'chat.view_details': 'Clic para ver detalles',
  }
};

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>(() => {
    // 1. Check local storage
    const saved = localStorage.getItem('app_language') as Language;
    if (saved && ['zh', 'en', 'es'].includes(saved)) return saved;

    // 2. Check browser language
    if (typeof navigator !== 'undefined') {
      const browserLang = navigator.language.toLowerCase();
      if (browserLang.startsWith('zh')) return 'zh';
      if (browserLang.startsWith('en')) return 'en';
      if (browserLang.startsWith('es')) return 'es';
    }

    // 3. Default
    return 'es';
  });

  useEffect(() => {
    localStorage.setItem('app_language', language);
  }, [language]);

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  const formatPrice = (price: number) => {
    if (language === 'zh') {
      return `¥${price.toLocaleString()}`;
    } else {
      return `$${price.toLocaleString()}`;
    }
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, formatPrice }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
